name: jotcompose

include:
  - notebooks/compose.yaml
  - notes/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.29.4-alpine
    ports:
      - 8888:80
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    networks:
      - api-net
    restart: unless-stopped

networks:
  api-net:
