name: notebooks

services:
  notebooks:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${NOTEBOOKS_IMAGE_DOMAIN:-notebooks}/notebooks:latest
    depends_on:
      notebooks-db:
        condition: service_healthy
    env_file:
      - .env.db.user
    environment:
      - MONGODB_HOST=notebooks-db
      - MONGODB_PORT=27017
      - NOTES_HOST=${NOTES_HOST}
      - NOTES_PORT=${NOTES_PORT}
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "/app/healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notebooks-net
      - api-net

  notebooks-db:
    image: mongodb/mongodb-community-server:7.0-ubi8
    env_file:
      - .env.db.root
      - .env.db.user
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: notebooks-data
        target: /data/db
    networks:
      - notebooks-net

volumes:
  notebooks-data:

networks:
  notebooks-net:
  api-net:
